return {
  ["workshop-1207269058"]={ configuration_options={  }, enabled=true },
  ["workshop-1803285852"]={
    configuration_options={
      [""]=0,
      AutoPickupAsh=false,
      AutoPickupEnabled=false,
      AutoPickupPoop=false,
      AutoPickupRange=10,
      AutoPickupSeeds=false,
      AutoStackAsh=false,
      AutoStackEnabled=true,
      AutoStackMakeNewStackMainStack=true,
      AutoStackManuallyDroppedItems=false,
      AutoStackPoop=false,
      AutoStackRange=10,
      AutoStackSeeds=false,
      AutoStackTwiggyTreeTwigs=false,
      ManualDropStackRange=5,
      ManualStackAsh=false,
      ManualStackMakeNewStackMainStack=false,
      ManualStackPoop=false,
      ManualStackSeeds=false,
      PlayerMustHaveOneOfItemToAutoPickup=false,
      SmokePuffOnStacking=true,
      StackDuringPopulation=false 
    },
    enabled=true 
  },
  ["workshop-2798599672"]={
    configuration_options={
      config_render=true,
      slot_amulet="extrabody3",
      slot_armor="extrabody1",
      slot_clothing="extrabody2" 
    },
    enabled=true 
  },
  ["workshop-3138571948"]={
    configuration_options={
      COMPLETESYNC=true,
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      GLOBAL_COURIER=true,
      OVERRIDEMODE=false,
      REMOVE_GHOST_ICONS=true,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2,
      Space1=0,
      UPDADTEFREQUENCY=0.5,
      disable_fogrevealer=false,
      lang="auto",
      optimization_tile=0,
      remove_maprevealer_tag=false,
      use_optimizer=false 
    },
    enabled=true 
  },
  ["workshop-810443397"]={
    configuration_options={
      FRESH=false,
      GIVE=false,
      LANG=1,
      LIGHT=false,
      RECIPE=1,
      STACK=false,
      WALKSPEED=1 
    },
    enabled=true 
  } 
}